# Copyright (C) 2022 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: BSD-3-Clause

name: Build and Test

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt

      - name: Install package
        run: |
          pip install -e .

      - name: Run tests and build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing --cov=kscore tests/ | tee pytest-coverage.txt

      - name: Add pytest coverage comment to PR/commit
        if: matrix.python-version == '3.8'
        id: coverage_comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Check the output coverage
        if: matrix.python-version == '3.8'
        run: |
          coverage=${{ steps.coverage_comment.outputs.coverage }}
          coverage=${coverage%"%"}
          min_coverage=85
          if ((coverage < ${min_coverage})); then
            echo "Coverage Percentage - ${{ steps.coverage_comment.outputs.coverage }} is below required ${min_coverage}%"
            exit 1
          else
            echo "Coverage Percentage - ${{ steps.coverage_comment.outputs.coverage }}"
          fi
